version: '3.8'

services:

  # PostgreSQL database service
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # App service
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npx", "prisma", "migrate", "deploy"]
    container_name: node-migrations
    env_file:
      - .env
    environment:      
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    depends_on:
      postgres:
        condition: service_healthy

  # App service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      VITE_SERVER_URL: ${VITE_SERVER_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"  # Map the environment variable for the port
    depends_on:
      - migrations

# Volumes to persist PostgreSQL data
volumes:
  pgdata: